### ISSUE TITLE
Failed to determine if remote branch exists - auth problem

### ISSUE THREAD

**Issue by tochamateusz** [ldelossa/gh.nvim#105]
I find some troubles when I clone my repository with token included in URL.
![Peek 2024-01-13 14-06](https://github.com/ldelossa/gh.nvim/assets/146367889/153f2ae5-ada3-4494-b204-17f90b3b2615)

I was able to fix it with:
https://github.com/ldelossa/gh.nvim/pull/104

**Comment by aburd** [comment]
Since the corresponding fix was merged, I think this issue can be closed
