### ISSUE TITLE
Comments posted on a pending review get extra quote wrapping

### ISSUE THREAD

**Issue by joestringer** [ldelossa/gh.nvim#118]
If you start a pending review, then use `GHCreateThread` and post a comment onto some code, the output in the target PR looks like:

```
'
This is the message in the review comment. Any '\''apostraphe'\'' comes out looking like this.
'
```

What I would expect to see is the verbatim comment:

```
This is the message in the review comment. Any 'apostraphe' comes out looking like this.
```

The same issue also occurs when submitting a review with a top-level comment.

**Comment by joestringer** [comment]
Not really obvious to me how this code ends up with that result:

https://github.com/ldelossa/gh.nvim/blob/cd79791b8ccddbf167ca766331b05a4d33eb9d3e/lua/litee/gh/ghcli/init.lua#L827

This didn't previously happen, so I'm not sure if this is related to my `gh` tool version or something in the libraries here that has changed.

For reference:
```
$ gh --version
gh version 2.52.0 (2024-06-24)
https://github.com/cli/cli/releases/tag/v2.52.0
```

**Comment by joestringer** [comment]
For reference the input is already malformed before it gets into `gh` CLI:

Enabled `debug_logging` in the config:
```
require('litee.gh').setup({debug_logging = true})
```

Then submitted a new comment with the value `test a new reply` and opened `GHOpenDebugBuffer`. We already see the extra quotes here:

```
[info] [gh] cmd: { "gh", "api", "graphql", "-F", "pull=...", "-F", "review=...", "-F", "commit=...", "-F", "body='test a new reply'", ...
```

**Comment by joestringer** [comment]
Oh that would do it:

https://github.com/ldelossa/gh.nvim/blob/cd79791b8ccddbf167ca766331b05a4d33eb9d3e/lua/litee/gh/pr/thread_buffer.lua#L95

**Comment by rmacklin** [comment]
I'm unable to look deeply at the moment, but might it be related to https://github.com/ldelossa/gh.nvim/commit/d6afb4f61dc45582ed6e6d85fc024f191d832cc8 (the same commit you linked to in #117)? Seems like some gh commands were changed from strings (which included `gh` itself to lists (with just the args after `gh`), so perhaps there was some escaping that was needed before that commit which is no longer needed.

**Comment by joestringer** [comment]
@rmacklin ha, indeed it looks like we found it at the same time. I've posted a PR with the proposal. I didn't vet whether there are any other callers that might still need the escaping, so let me know if there's anything I missed there. Should fix it though.

**Comment by rmacklin** [comment]
There may be similar extra escaping happening in the other `extract_text` methods for commits/issues:
https://github.com/ldelossa/gh.nvim/blob/ebbaac254ef7dd6f85b439825fbce82d0dc84515/lua/litee/gh/commits/commit_buffer.lua#L386
https://github.com/ldelossa/gh.nvim/blob/ebbaac254ef7dd6f85b439825fbce82d0dc84515/lua/litee/gh/issues/issue_buffer.lua#L424
and possibly in pull request review submission comments:
https://github.com/ldelossa/gh.nvim/blob/ebbaac254ef7dd6f85b439825fbce82d0dc84515/lua/litee/gh/pr/init.lua#L725
https://github.com/ldelossa/gh.nvim/blob/ebbaac254ef7dd6f85b439825fbce82d0dc84515/lua/litee/gh/pr/init.lua#L768
but I'm unable to test currently.
