### ISSUE TITLE
Order of splits in diff view

### ISSUE THREAD

**Issue by jcrespy-dlg** [ldelossa/gh.nvim#127]
Unless I'm doing something wrong, when looking at a diff with split view, the "new" version of the file is shown on the left, and "old" version on the right. Is there any way to invert this ? It's very confusing to me, as it is not coherent with other plugins I use that have diff views, and not coherent with the github website way of showing a diff.

**Comment by ldelossa** [comment]
@jcrespy-dlg 

your vim is probably configured to open splits on a side that nvim-ide does not expect. 

Try playing with the "set splitright" config option and related ones. If you enable or disable it, does this fix things? 

I recall running into this on someones config. Gh.nvim just does a plain "vsplit" to create the diff windows. But your vim is configured to either create that split toward the right or left. I dont recall off the top of my head whether it should be created on right or left, but if you find the config for this, swap it, and see if it fixes the issue.

**Comment by jcrespy-dlg** [comment]
Thank you, this was exactly this. I had `vim.opt.splitright = true` in my config.

**Comment by ldelossa** [comment]
Awesome, love an easy fix :)
