### ISSUE TITLE
FzfLua register_ui_select opens second prompt in NORMAL mode

### ISSUE THREAD

**Issue by strdr4605** [ldelossa/gh.nvim#17]
When I run `GHSubmitReview`, the FzfLua popup asks me if I want to approve, comment, etc...
When I select approve a new popup asks if I want to add a comment or not. 
But I can not select any option because I am in NORMAL mode, and not TERMINAL mode as in the previous popup.

I know that this issue may not be strictly related to **gh.nvim**. But maybe you also had this issue.

[My fzf-lua config](https://github.com/strdr4605/.dotfiles/blob/master/nvim/lua/user/fzf-lua.lua), if it helps.

**Comment by ldelossa** [comment]
This occurs for me too, you have to hit "i" to get into insert mode at the second dialogue, right?

**Comment by strdr4605** [comment]
Yes, I need to press "i" to be able to select. Thanks
> I am new to vim

Any ideas on how this can be solved?

**Comment by ldelossa** [comment]
Not exactly, like you mentioned, this is infact not really something `gh.nvim` is responsible for. I would try to bring this up in fzf.lua's repository and link to this issue. I can provide further explanation there if needed.

**Comment by strdr4605** [comment]
Ok, thanks. You might close this for now.
