### ISSUE TITLE
Detach LSPs on left side of diff view

### ISSUE THREAD

**Issue by ldelossa** [ldelossa/gh.nvim#19]
Things get real weird when LSP's are attached to the tmp file created to diff the original file and the changed file sititng locally on the FS. 

Detach any LSPs on the tmp file on the left side of diff to avoid this.

**Comment by Frederick888** [comment]
FWIW I'm using [gopls](https://github.com/golang/tools/tree/master/gopls/) and most of things actually work on the left side somehow.

**Comment by ldelossa** [comment]
Yeah, tbh, I encountered an error once from this, but never again. 

Closing.
