### ISSUE TITLE
Should gh.nvim config.prefer_https_remote use gh config?

### ISSUE THREAD

**Issue by dlvhdr** [ldelossa/gh.nvim#28]
The gh config already stores the user preference for https/ssh.
Do you think you should respect that as well? as all the other actions use gh under the hood I'm assuming.

**Comment by ldelossa** [comment]
Aha! 

```
🖭  gh config list
git_protocol=ssh
editor=
prompt=enabled
pager=
http_unix_socket=
browser=
```

That would be pretty cool, and probably the right thing to do, so you're thinking, on gh.nvim startup, do something like:

```
🖭  gh config get git_protocol
https
```

and then automatically set the git remote accordingly?

**Comment by dlvhdr** [comment]
Yes I think thats the approach

**Comment by ldelossa** [comment]
Would you want to take on that PR? Seems relatively straight forward.

**Comment by dlvhdr** [comment]
Yeah I can do that

**Comment by ldelossa** [comment]
Cool, we may want an "auto" flag in the "prefer_https_remotes" config value, where we dynamically look it up. This then still allows the user to force "ssh" or "https" if they want to. Maybe its useful?

**Comment by dlvhdr** [comment]
My intuition is that a user wouldn't need to define a different protocol for gh.nvim that is different than `gh`.
I would add it in the future if there's an interest but I could be wrong here

**Comment by ldelossa** [comment]
@David-Kunz in issue #15 you had to flip the "prefer_https_remote" flag in your private repo. 

In this issue we are trying to determine if we looked at the "gh config list" command and set the remote type with the setting in there, would it have set the correct remote for you? 

Could you run that command in your private repo where you're using the "prefer_https_remote" flag and tell us the value of the "git_protocol" config.

**Comment by David-Kunz** [comment]
Hi @ldelossa,

When I execute `gh config list`, the value is `gh_protocol=https`.

Best regards,
David

**Comment by ldelossa** [comment]
Cool, thanks @David-Kunz. 

a little unscientific @dlvhdr but seems like on all our systems the gh cli matches the git protocol that works. Just wanted to make sure.

**Comment by ldelossa** [comment]
Closed! Thanks again @dlvhdr

**Comment by ldelossa** [comment]
Thank occurred just now:

```
~/git/vim/litee-gh-testing remotes/litee-gh_ldelossa/litee-gh-testing/branch-1
🖭  gh config list
git_protocol=ssh
editor=
prompt=enabled
pager=
http_unix_socket=
browser=

~/git/vim/litee-gh-testing remotes/litee-gh_ldelossa/litee-gh-testing/branch-1
🖭  gh config get git_protocol
https
``` 

Weird lol. I manually set it to get it to work again.

```
~/git/vim/litee-gh-testing main
🖭  gh config set git_protocol ssh

~/git/vim/litee-gh-testing main
🖭  gh config get git_protocol    
ssh
```
