### ISSUE TITLE
Consider using glow for rendering the markdown

### ISSUE THREAD

**Issue by dlvhdr** [ldelossa/gh.nvim#29]
In gh-dash I'm using https://github.com/charmbracelet/glow to render the markdown.
I think it works pretty well and adds nice visuals

**Comment by ldelossa** [comment]
Hey, 

Looks cool, in practice how would this work with Neovim's TUI? Seems like glow 
is it's own CLI which I assume writes color codes?

**Comment by dlvhdr** [comment]
They provide a Go library you can use, so easy as pie

**Comment by ldelossa** [comment]
Im not exactly following how this would equate to highlighted text in a Neovim buffer? 

I think the way to do this is with a markdown treesitter parser in Neovim. Unless you have another idea?

**Comment by dlvhdr** [comment]
Ah ok I see what you're saying... I'd to think more then

**Comment by ldelossa** [comment]
Closing this for now feel free to reopen
