### ISSUE TITLE
More Robust Error Handling

### ISSUE THREAD

**Issue by bradsherman** [ldelossa/gh.nvim#31]
I've had a few issues this morning using the plugin. I'm happy to help debug, but I'm not sure exactly where I can find more information about the errors. Specifically, I've had the following happen to me:

1. Sometimes I can not even open a PR right after starting nvim - I get `failed to fetch remote branch` in what appears to be the 'fetching checks' stage.
2. When trying to open a PR while one is already open, I enter 'yes' and get the following error:
  ```
E5108: Error executing lua .../site/pack/packer/start/gh.nvim/lua/litee/gh/pr/init.lua:365: attempt to index field 'state' (a nil value)
stack traceback:
        .../site/pack/packer/start/gh.nvim/lua/litee/gh/pr/init.lua:365: in function 'close_pull'
        .../site/pack/packer/start/gh.nvim/lua/litee/gh/pr/init.lua:216: in function 'callback'
        ...er/start/dressing.nvim/lua/dressing/select/telescope.lua:58: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:242: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
  ```
3. I also get the following error when trying to explicitly close an open PR:
```
Error executing Lua callback: .../site/pack/packer/start/gh.nvim/lua/litee/gh/pr/init.lua:365: attempt to index field 'state' (a nil value)
stack traceback:
        .../site/pack/packer/start/gh.nvim/lua/litee/gh/pr/init.lua:365: in function <.../site/pack/packer/start/gh.nvim/lua/litee/gh/pr/init.lua:344>
```

**Comment by bradsherman** [comment]
Ah, I assumed my `gh config` was correctly set to ssh. Setting that value correctly fixes the issues. Is there somewhere I can inspect the output of the commands? That would be helpful for debugging issues like this

**Comment by bradsherman** [comment]
yeah I think I could look into that. My first thought is to doing something like what null-ls does https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/logger.lua. I've flipped the `debug` flag on to diagnose issues with null-ls in the past

**Comment by ldelossa** [comment]
Looks cool. Im down for whatever. My only request is try to build something into litee.nvim or gh.nvim directly. 

I have no problems with planetary, but we already require litee.nvim, and i dont want the depedencies to grow even further.

**Comment by ldelossa** [comment]
Think https://github.com/ldelossa/gh.nvim/pull/63 closes this issue. 

It only logs cli interactions, but I think this is where 99.99% of the issues with gh.nvim creep up. Closing for now.
