### ISSUE TITLE
Bug: Fail to list PRs

### ISSUE THREAD

**Issue by Aceticia** [ldelossa/gh.nvim#39]
macOS Monterey, non-M1, tested on nvim stable and nightly. I'm just using the default settings for everything. In a repo with an active pull request, calling `:GHOpenPR` returns a message of `Failed to list PRs.` Ensured that both plugins are installed and up. Is there some type of log that I can post here so debugging is easier?

**Comment by ldelossa** [comment]
Hey there, debugging is pretty rough right now, maybe youd be interested in helping out with: https://github.com/ldelossa/gh.nvim/issues/31

**Comment by ldelossa** [comment]
For your actual issue, did you confirm your gh tools "git_protocol" config setting is correct? Also if youre using ssh are you keys? 

Failing to list happens very early. Can you do a "gh pr list" with the "gh" directly in that repo?

**Comment by ldelossa** [comment]
Closing this for now. Reopen if youre still encountering issues
