### ISSUE TITLE
Message on startup

### ISSUE THREAD

**Issue by lervag** [ldelossa/gh.nvim#40]
Hi. I like your project and believe I will be using it. However, after a relatively recent update, gh.nvim will echo "[gh.nvim] started background refresh with interval 3 minutes" when I start neovim. It does not seem useful and at the very least, it seems out of place in this context. I suggest either of the following actions:

* Remove this message in general.
* Do not show message on neovim start, but rather whenever any gh.nvim related contexts is opened.
* Any of the above with an option to control the behaviour.

Also: The background refresh is not explained in the docs and it is unclear what it is.

**Comment by ldelossa** [comment]
Its touched on here: https://who.ldelossa.is/posts/gh-nvim/#cli-dependencies

The background refresh keeps gh.nvim in sync with the GitHub api. But it wont do much if a pr is not open, or issue buffers arent open. Its required to get new comments / new PR commits / etc... automatically.

**Comment by lervag** [comment]
Ok, thanks! Still, I think the echo on neovim startup is unnecessary. Would you mind to make it optional?

**Comment by ldelossa** [comment]
Sounds find to me. Want to send a PR for this? Ill approve.

**Comment by lervag** [comment]
I'm looking into it. I'm wondering: do we really need to start the refresh timer within `init.lua`:

https://github.com/ldelossa/gh.nvim/blob/caed363e5227fd32e977960543ad86a09c827979/lua/litee/gh/init.lua#L265

I mean, it is understandable that we want this timer when we open a PR or issue, but do we want it already when a user does the `setup()` function?

My intuition would be that we could just remove that line. It would resolve my issue. But perhaps I'm missing something?

**Comment by ldelossa** [comment]
The timer is used to refresh arbitrary Issue buffers which can be open at any time, and unrelated to having an open PR. 

Its a lot simpler to just launch the timer which runs a no-op function if no Issues or PR is open, rather then trying to ref count open Issue buffers or open PRs. The no-op timer is not going to effect UX of performance when no Issue or PR buffers are open.

**Comment by lervag** [comment]
Closing this as we can continue the discussion in #42.
