### ISSUE TITLE
Slow Startup

### ISSUE THREAD

**Issue by dnjp** [ldelossa/gh.nvim#41]
With gh.nvim disabled, `--startuptime` is showing neovim takes about 80ms to initialize with the plugins I have active. Once I enable gh.nvim, this number jumps to about 600ms. I initially thought that some of this load time was due to the scheduling of [the print statement](https://github.com/ldelossa/gh.nvim/blob/main/lua/litee/gh/init.lua#L252) when gh.nvim launches, but after commenting it out that only cut the load time down to about 450ms. The only solution that keeps my startup time to <100ms is to configure gh.nvim in the following way:

```lua
return require('packer').startup(function()
        ...
	use {
		'ldelossa/gh.nvim',
		requires = { { 'ldelossa/litee.nvim' } },
	}
	...
end)

function SetupGithub()
	require('litee.lib').setup()
	require('litee.gh').setup({
	  ...
	})
end
vim.schedule(SetupGithub)
```

I have not done any deeper profiling of gh.nvim to determine where the latency is coming from, but given my "solution" I suspect it has due to do with initializing litee.

**Comment by ldelossa** [comment]
We do an initial cache of the github user data. Its synchronous, since other portions of the plugin require it. I suspect thats where it comes from. Is the delay noticeable or are you just measuring?

**Comment by ldelossa** [comment]
Does it get better by removing the user caching? If so i can make that lazily evaluated somehow

**Comment by dnjp** [comment]
That definitely fixes the problem. Commenting out the user cache init function like this:
```
M.user = {}
-- local function init()
--    M.user = M.get_user()
-- end
-- init()
```
brings the startup time down to <100ms. Uncommenting that block brings it back up to around 400-500ms.

**Comment by ldelossa** [comment]
Cool, I'll rework that and clear up the blocking. Thanks for the numbers. Appreciate the digging

**Comment by dnjp** [comment]
No problem. Thanks for the great plugin!

**Comment by ldelossa** [comment]
Fixed in latest commits @dnjp

**Comment by dnjp** [comment]
@ldelossa That resulted in a huge improvement in the startup time. Thanks!
