### ISSUE TITLE
Loading a PR can get stuck at the "fetching checks" stage

### ISSUE THREAD

**Issue by joestringer** [ldelossa/gh.nvim#44]
While trying to open https://github.com/cilium/cilium/pull/19159, I'm hitting an issue where gh.nvim gets stuck "fetching checks". It does not appear to proceed beyond this point.

For some context, at this time there are checks in various stages, including passed, failed, skipped and required-but-not-run (probably due to some upstream GitHub bug):
![image](https://user-images.githubusercontent.com/1243336/171517401-0255304f-d1a8-407f-aa6e-0dc9de637fec.png)

**Comment by joestringer** [comment]
^ Of course, when I closed nvim and retried, it just worked. Hmm. I'll be happy to turn on any sort of debug suggestions to try to grab some more info when this occurs.

**Comment by ldelossa** [comment]
Argh, running into this too. My assumptions is that on the first load of the PR we don't reset the the pull request state to nothing. 

We don't do that, cuz the same method is ran *after* the the PR is open, and if something fails then, we don't wanna wipe out all the existing PR state. So I gotta find a good way to handle that.
