### ISSUE TITLE
Doesn't work with nvim-tree

### ISSUE THREAD

**Issue by rmcclaincf** [ldelossa/gh.nvim#51]
When nvim-tree is enabled, most things don't work.   For example, opening a diff in "Files Changed" causes the diff buffer to appear for a moment and then disappear.

**Comment by ldelossa** [comment]
Does this work if nvim-tree is toggled closed?

**Comment by rmcclaincf** [comment]
It seems when the tree is toggled close, I can get a diff of a file under Files Changed, but I'm unable to expand directories.   Modified directories are collapsed and I'm not sure how to expand them.   Is there a hotkey I should be using other than Enter?

**Comment by ldelossa** [comment]
You can view the keymap here: https://github.com/ldelossa/gh.nvim/blob/3d489e4562dc1c249556142586f8c6477ed934b7/doc/gh-nvm.txt#L361

**Comment by ldelossa** [comment]
Itll take a bit to look into compatibility issues with nvim-tree. I dont use the plugin. Ideally, gh.nvim has no need for a tree plugin to be used as well, but i do think it shouldnt break its functionality.

**Comment by rmcclaincf** [comment]
I just made a key binding which closes nvim-tree when opening a PR and vice versa.  Seems to be good enough.

**Comment by DennisTheMenace780** [comment]
> I just made a key binding which closes nvim-tree when opening a PR and vice versa. Seems to be good enough.

Would you mind sharing what the key binding is @rmcclaincf ? I'm running into the same issue.
