### ISSUE TITLE
GHClosePR has Invalid Window

### ISSUE THREAD

**Issue by natdm** [ldelossa/gh.nvim#62]
Running `GHOpenPR`, selecting a PR, then immediately running `GHClosePR` results in this error:
![Screen Shot 2022-08-10 at 6 27 38 AM](https://user-images.githubusercontent.com/11272201/183913392-ade35858-a2a5-473a-b485-7c9f7100038f.png)

I just updated GH yesterday so I should be on the newest. 

Also might be a good idea to state that GHClosePR closes neovims instance of a PR, *not* the original PR. Made me hesitate to call it.

**Comment by ldelossa** [comment]
Hey @natdm 

Those errors are in a different plugin. Youll have to debug shade.nvim first.

**Comment by natdm** [comment]
Oh man! Good catch, thank you.

**Comment by ldelossa** [comment]
Np! If you debut there, and it winds up being something between the interaction of the plugins, i can help further. 

But, it looks like shade.nvim just needs to do a "nvim_win_is_valid" check on the area where the stacktrace presents.
