### ISSUE TITLE
Feature request: Show diff between current and target branches in per-file diff view

### ISSUE THREAD

**Issue by Frederick888** [ldelossa/gh.nvim#70]
At the moment in per-file diff views, it shows the difference from the common ancestor between current and target branches [1].

This gives different results from GitHub web. It'd be nice if this can be configured to head of target branch. (We all have to work with someone who just _loves_ merging master/main into PR branches, don't we ;) )

[1] https://github.com/ldelossa/gh.nvim/blob/20604033b61db43173f85a5b3cfc793089232d1d/lua/litee/gh/pr/diff_view.lua#L436

**Comment by GuillaumeLagrange** [comment]
@Frederick888 I don't know if you're still interested by this has been fixed

@ldelossa we can close this :tada:

**Comment by ldelossa** [comment]
Thanks @GuillaumeLagrange appreciated!
