### ISSUE TITLE
Failed to submit review

### ISSUE THREAD

**Issue by PaulKushch** [ldelossa/gh.nvim#76]
Hi,
Thanks for the great plugin!

I have a problem, I always get `Failed to submit review` when doing `:GHSubmitReview`. I also cannot do `:GHCreateThread` if review is pending. Because I get`Failed to create new comment` after writing something then. 

Is this something trivial I am missing? I can do `:GHCreateThread` outside of PR review still.

**Comment by faustind** [comment]
Hey @PaulKushch,
I am having the same trouble creating comments in pending PR mode. What is the solution you have found? Would you share it please 🙏🏾
