### ISSUE TITLE
not defaulting to telescope with lazy.nvim

### ISSUE THREAD

**Issue by sf8193** [ldelossa/gh.nvim#80]
Hello, your plugin looks amazing and exactly what i've been looking for. Can't stand the temptation to go to function definition with octo knowing that it's not possible. 

when I run `GHOpenPr` i get the regular ui view, not telescope. In the readme it's mentioned that it should default to telescope, however i don't see that and haven't been able to figure out where in the code that should be happening. I'm wondering if there's any guidance i'm missing or if this is something else.

Thank you for making the plugin again, really hopeful it solves the need i have

**Comment by ldelossa** [comment]
Hey, 

telescope (or fzf) you should overwrite the "vim.ui.select" function. 

Telescope should do this by default

**Comment by DennisTheMenace780** [comment]
I'm also experiencing a similar problem, but I do not use `lazy.nvim`. I have just grabbed the default configuration and tried to do a `GHOpenPr` as well and Telescope does not take over automatically.

**Comment by sf8193** [comment]
i believe you need the telescope-ui.nvim plugin that defaults to telescope? it won't default otherwise
