### ISSUE TITLE
Trying to open a PR throws error

### ISSUE THREAD

**Issue by dlvhdr** [ldelossa/gh.nvim#9]
Not sure, but I think the plugin got stuck on fetching contributors (`⣷ fetching repository contributors`). It's my company's private repo, so maybe it times out because of too many contributors.
The error I get is: 

```
Error executing luv callback:
...te/pack/packer/start/gh.nvim/lua/litee/gh/ghcli/init.lua:68: Expected the end but found T_ARR_BEGIN at character 100610
stack traceback:
        [C]: in function 'decode'
        ...te/pack/packer/start/gh.nvim/lua/litee/gh/ghcli/init.lua:68: in function <...te/pack/packer/start/gh.nvim/lua/litee/gh/ghcli/init.lua:59>
```

**Comment by ldelossa** [comment]
Are you using HEAD? At the least, we shouldn't see that error anymore, since json functions are wrapped in "pcall" and error checked. Hmm. Let me look into this a bit if you are.

**Comment by ldelossa** [comment]
Also, does it work with a public repo? Youre not the only one having issue with private repos.

**Comment by ldelossa** [comment]
@dlvhdr I think you hit the nail on the head with "too many collaborators". This is ultimately the same issue as: #8 
Going to close this one and lets track at #8
