### ISSUE TITLE
Manage file viewed state in PR

### ISSUE THREAD

**Issue by GuillaumeLagrange** [ldelossa/gh.nvim#98]
Hello,

Once again, thanks for the awesome plugin.
I would love a feature to handle file viewed states in PRs, which is really usefull for huge PRs that get updated between reviews.

Github provides the feature in its UI top right of diffs here and it gets unchecked if the file changes after the review

![image](https://github.com/ldelossa/gh.nvim/assets/19265358/d917bb67-cd8b-4353-9d9b-29e2c5d8499c)

I could not find stuff about it in the rest API from github, but I saw the `viewerViewedState` attribute in the graphql `PullRequestChangedFile` object: https://docs.github.com/en/graphql/reference/objects#pullrequestchangedfile

We could maybe build something around it ?

I think we can decompose this in two different parts

- [x] Add a visual feedback of the viewed state in the PR status tree next to the file names
- [x] Provide a way to manipulate this viewed state (toggle, viewed, and not viewed)

If it seems sensible I will look into it, not very familiar with graqhql apis though but they seem quite cool

**Comment by ldelossa** [comment]
Yes sounds like a great feature! 

If you want to take this on ill gladly review.

**Comment by GuillaumeLagrange** [comment]
Indeed it is !

Looks like this queries what I need, and even more with the changed type.

```
query {
  repository(owner: "guillaumelagrange", name: "neoconf-repro") {
    pullRequest(number: 1) {
      id
      author {login }
      files(first: 50) {
        edges {
          node { path, viewerViewedState, changeType }
        }
      }
    }
  }
}
```

This makes me think: should we add another request to the series of callbacks done in `pr/state.lua`  or replace an existing REST API call ?

It looks to me like we could migrate the whole `get_pull_files` request to the GraphQL API. And maybe all of the requests, though I am not sure I want to go down that rabbit hole without a good reason

**Comment by ldelossa** [comment]
As a general principle, i always try to accomplish something with REST api if possible and graphql only if it's the only way. Thats just a rule of thumb tho, not a hard and fast rule. 

If things get easier but migrating to a single graphql call, I'm not opposed, but rest is usually quick enough. May need to test how slow things get if that rest call is made for every single file in the pr.
